'use script'

let start = document.getElementById('start'),
	budget = document.getElementByClassName('budget-value'),
	daybudget = document.getElementByClassName('daybudget-value'),
	level = document.getElementByClassName('level-value'),
	expenses = document.getElementByClassName('expenses-value'),
	optionalexpenses = document.getElementByClassName('optionalexpenses-value'),
	income = document.getElementByClassName('income-value'),
	monthsavings = document.getElementByClassName('monthsavings-value'),
	yearsavings = document.getElementByClassName('yearsavings-value'),
	expensesItem1 = document.getElementsByClassName('expenses-item')[0],
	expensesItem2 = document.getElementsByClassName('expenses-item')[1],
	expensesItem3 = document.getElementsByClassName('expenses-item')[2],
	expensesItem4 = document.getElementsByClassName('expenses-item')[3],
	data = document.getElementByClassName('data'),
	btn1 = data.getElementByTagName('button')[0],
	btn2 = data.getElementByTagName('button')[1],
	btn3 = data.getElementByTagName('button')[2],
	optionalexpensesItem = document.querySelectorAll('.optionalexpenses-item'),
	chooseIncome = document.querySelector('.choose-income'),
	savings = document.querySelector('#savings'),
	chooseSum = document.querySelector('.choose-sum'),
	choosePercent = document.querySelector('.choose-percent'),
	yearValue = document.querySelector('.year-value'),
	monthValue = document.querySelector('.month-value'),
	dayValue = document.querySelector('.day-value');